# Generated by GPT-5.4 on 2026-07-04

from django.db import migrations


DEFAULT_CATEGORIES = [
    ('DIESEL', 'Diesel'),
    ('ELECTRICITY', 'Electricity'),
    ('INTERNET', 'Internet'),
    ('DSTV', 'DSTV'),
    ('MAINTENANCE', 'Maintenance'),
    ('TRANSPORT', 'Transport'),
    ('LAUNDRY', 'Laundry'),
    ('CLEANING_SUPPLIES', 'Cleaning Supplies'),
    ('WATER', 'Water'),
    ('MARKETING', 'Marketing'),
    ('REPAIRS', 'Repairs'),
    ('OFFICE_SUPPLIES', 'Office Supplies'),
    ('SECURITY', 'Security'),
    ('SALARY', 'Salary'),
    ('TAXES', 'Taxes'),
    ('MISCELLANEOUS', 'Miscellaneous'),
]


def seed_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    for code, name in DEFAULT_CATEGORIES:
        ExpenseCategory.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'description': '',
                'is_active': True,
            },
        )


def unseed_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    codes = [code for code, _name in DEFAULT_CATEGORIES]
    ExpenseCategory.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
