# Generated by Django 6.0.5 on 2026-06-04 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_id_alter_customuser_role_auditlog'),
        ('customers', '0002_customer_created_by_and_created_at'),
        ('stays', '0002_gueststay_checked_in_at_gueststay_checked_in_by_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('customer_created', 'Customer Created'), ('customer_updated', 'Customer Updated'), ('booking_created', 'Booking Created'), ('booking_edited', 'Booking Edited'), ('guest_checked_in', 'Guest Checked In'), ('guest_checked_out', 'Guest Checked Out')], max_length=50)),
                ('user_full_name', models.CharField(max_length=255)),
                ('user_username', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stays.gueststay')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
