# Generated by Django 6.0.6 on 2026-07-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_default_job_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.AddField(
            model_name='customuser',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.jobposition'),
        ),
    ]
