# Generated by Django 6.0.6 on 2026-07-05 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sync_default_job_positions_multi_position_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profiles/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain only letters, numbers, periods, and underscores.', regex='^[A-Za-z0-9._]+$')]),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_edited', 'User Edited'), ('user_status_changed', 'User Status Changed'), ('first_login_completed', 'First Login Completed'), ('username_changed', 'Username Changed'), ('email_changed', 'Email Changed'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset by Admin'), ('profile_updated', 'Profile Updated'), ('profile_photo_updated', 'Profile Picture Updated'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('product_toggled', 'Product Toggled'), ('inventory_created', 'Inventory Created'), ('inventory_updated', 'Inventory Updated'), ('inventory_deleted', 'Inventory Deleted'), ('inventory_stock_added', 'Inventory Stock Added'), ('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_deleted', 'Task Deleted'), ('staff_rated', 'Staff Rated')], max_length=50),
        ),
    ]
