# Generated by Django 6.0.6 on 2026-07-08 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_backfill_existing_user_onboarding_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='module_permissions_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_edited', 'User Edited'), ('user_status_changed', 'User Status Changed'), ('first_login_completed', 'First Login Completed'), ('username_changed', 'Username Changed'), ('email_changed', 'Email Changed'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset by Admin'), ('profile_updated', 'Profile Updated'), ('profile_photo_updated', 'Profile Picture Updated'), ('module_permission_created', 'Module Permission Created'), ('module_permission_disabled', 'Module Permission Disabled'), ('module_permission_granted', 'Module Permission Granted'), ('module_permission_revoked', 'Module Permission Revoked'), ('user_module_permissions_updated', 'User Module Permissions Updated'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('product_toggled', 'Product Toggled'), ('inventory_created', 'Inventory Created'), ('inventory_updated', 'Inventory Updated'), ('inventory_deleted', 'Inventory Deleted'), ('inventory_stock_added', 'Inventory Stock Added'), ('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_deleted', 'Task Deleted'), ('staff_rated', 'Staff Rated')], max_length=50),
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('module_url_name', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='module_permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.modulepermission'),
        ),
    ]
