# Generated by Django 6.0.6 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_backfill_ops_manager_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='manages_positions',
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    'Positions that a holder of this position is authorized to assign tasks to, '
                    'independent of the reports_to chain. E.g. "Bar Supervisor" can manage_positions '
                    '"Barman" and "Bartender" without needing an org-chart link.'
                ),
                related_name='managed_by_positions',
                to='accounts.jobposition',
            ),
        ),
    ]
