# Generated by Django 6.0.5 on 2026-06-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_gueststay_checked_in_at_gueststay_checked_in_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gueststay',
            name='checked_in_by_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='checked_in_by_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='checked_in_by_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='checked_out_by_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='checked_out_by_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='checked_out_by_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='created_by_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='created_by_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gueststay',
            name='created_by_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
