# Generated by Django 6.0.5 on 2026-06-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('item_name', 'category')},
        ),
    ]
