# Generated by Django 6.0.5 on 2026-06-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_created_by_and_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
