# Generated by Django 6.0.5 on 2026-06-03 01:30

from django.db import migrations


def ensure_date_assigned_column(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info('tasks_task')")
        columns = [row[1] for row in cursor.fetchall()]
        if 'date_assigned' in columns:
            return
        cursor.execute("ALTER TABLE tasks_task ADD COLUMN date_assigned date")
        cursor.execute("UPDATE tasks_task SET date_assigned = DATE('now') WHERE date_assigned IS NULL")


class Migration(migrations.Migration):
    from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop,
            migrations.RunPython.noop,
        ),
    ]

