# Generated by Django 6.0.5 on 2026-07-03 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('tasks', '0005_sync_task_timestamp_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='previous_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_tasks', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='requires_inspection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready_for_review', 'Ready for Review'), ('completed', 'Completed'), ('reopened', 'Reopened')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('role', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('bed_living', 'Bed & Living'), ('bathroom', 'Bathroom'), ('touchpoints', 'Touchpoints'), ('floors_waste', 'Floors & Waste'), ('amenities', 'Amenities')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('standard', 'Standard'), ('detail', 'Detail')], max_length=20)),
                ('deduction_points', models.PositiveIntegerField()),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_template_items_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.inspectiontemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_template_items_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('template', 'description')},
            },
        ),
        migrations.CreateModel(
            name='TaskInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_score', models.PositiveIntegerField(default=100)),
                ('total_deductions', models.PositiveIntegerField(default=0)),
                ('final_score', models.PositiveIntegerField(default=100)),
                ('result', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('pass', 'Pass'), ('fail', 'Fail')], max_length=20)),
                ('inspector_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_inspections_created', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_inspections_as_inspector', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='tasks.task')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='tasks.inspectiontemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_inspections_updated', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.PROTECT, related_name='task_inspections_as_worker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('deduction_applied', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_results', to='tasks.inspectiontemplateitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tasks.taskinspection')),
            ],
            options={
                'ordering': ['template_item__display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('inspection', 'template_item'), name='unique_result_per_template_item')],
            },
        ),
    ]
