# Generated by Django 6.0.6 on 2026-07-05 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobposition_customuser_position'),
        ('tasks', '0009_seed_default_maintenance_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_position',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_tasks', to='accounts.jobposition'),
        ),
    ]
