# Generated by Django 6.0.6 on 2026-07-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_position_customuser_positions'),
        ('tasks', '0010_task_required_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='required_position',
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='applicable_positions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='inspection_templates', to='accounts.jobposition'),
        ),
        migrations.AddField(
            model_name='maintenancecategory',
            name='assignable_positions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='maintenance_categories', to='accounts.jobposition'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_positions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='required_tasks', to='accounts.jobposition'),
        ),
    ]
