# Generated by Django 6.0.5 on 2026-06-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_created_by_full_name_and_more'),
        ('rooms', '0001_initial'),
        ('sales', '0003_alter_sale_id'),
        ('stays', '0003_gueststay_checked_in_by_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='sale',
            name='stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='stays.gueststay'),
        ),
    ]
