# Generated by Django 6.0.5 on 2026-07-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_customer_sale_room_sale_stay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Payment'), ('transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
